services:
  backend:
    container_name: hevy_backend
    image: casudo/hevy-insights-backend:latest
    restart: unless-stopped
    environment:
      - X_API_KEY=klean_kanteen_insulated
    hostname: hevy_backend

  frontend:
    container_name: hevy_frontend
    image: casudo/hevy-insights-frontend:latest
    restart: unless-stopped
    ports:
      - 8123:8080
    depends_on:
      - backend
    hostname: hevy_frontend
    labels:
      - "homepage.group=Fitness"
      - "homepage.name=Hevy Insights"
      - "homepage.icon=hevy"
      - "homepage.href=http://${HOST_IP}:8123"
      - "homepage.description=Workout analytics"
