version: "3.8"

networks:
  external:
    external: true
  internal:
    external: true

services:

  # image used to index torrent links from the internet
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker-configs/prowlarr:/config # database and Prowlarr configs
    security_opt:
      - no-new-privileges:true 
    ports:
      - 9696:9696/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:9696/prowlarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.moritzpalm.com`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      # Optional part for traefik middlewares
      #- traefik.http.routers.prowlarr.middlewares=local-ipwhitelist@file
      - homepage.group=Downloader
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=https://prowlarr.moritzpalm.com
      - homepage.description=Indexer Manager
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=$PROWLARR_API_KEY
      - homepage.widget.fields=["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]

  # image used to scan for tv shows
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./docker-configs/sonarr:/config # database and Radarr configs
      - $MEDIA_PATH:/data # location of media and qbittorrent download folder
    security_opt:
       - no-new-privileges:true 
    ports:
      - 8989:8989/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8989/sonarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.moritzpalm.com`) || Host(`sonarr.local.moritzpalm.com`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.sonarr.middlewares=local-ipwhitelist@file
      - homepage.group=Downloader
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=https://sonarr.moritzpalm.com
      - homepage.description=Series Indexer
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=$SONARR_API_KEY
      - homepage.widget.enableQueue=true
      - homepage.widget.fields=["wanted", "queued", "series"]

  # image used to scan for movies
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker-configs/radarr:/config
      - $MEDIA_PATH:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true 
    ports:
      - 7878:7878/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/radarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.moritzpalm.com`) || Host(`radarr.local.moritzpalm.com`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.sonarr.middlewares=local-ipwhitelist@file
      - homepage.group=Downloader
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=https://radarr.moritzpalm.com
      - homepage.description=Movies Indexer
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=$RADARR_API_KEY
      - homepage.widget.enableQueue=true
      - homepage.widget.fields=["wanted", "missing", "queued", "movies"]

  # image used to scan for music
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker-configs/lidarr:/config
      - $MEDIA_PATH:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true 
    expose:
      - 8686/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8686/lidarr/ping" ]
      interval: 30s
      retries: 10
    ports:
      - 8686:8686/tcp # web ui
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.moritzpalm.com`) || Host(`lidarr.local.moritzpalm.com`)"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.lidarr.service=lidarr"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.sonarr.middlewares=local-ipwhitelist@file
      - homepage.group=Downloader
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=https://lidarr.moritzpalm.com
      - homepage.description=Music Indexer
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://lidarr:8686
      - homepage.widget.key=$LIDARR_API_KEY
      - homepage.widget.fields=["wanted", "queued", "artists"]
      

  # image used to scan for books
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker-configs/readarr:/config
      - $MEDIA_PATH:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true
    ports:
      - 8787:8787/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8787/readarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.entrypoints=websecure"
      - "traefik.http.routers.readarr.rule=Host(`readarr.moritzpalm.com`) || Host(`readarr.local.moritzpalm.com`)"
      - "traefik.http.routers.readarr.tls=true"
      - "traefik.http.routers.readarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.readarr.service=readarr"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.sonarr.middlewares=local-ipwhitelist@file
      - homepage.group=Downloader
      - homepage.name=Readarr
      - homepage.icon=readarr.png
      - homepage.href=https://readarr.moritzpalm.com
      - homepage.description=Books Indexer
      - homepage.widget.type=readarr
      - homepage.widget.url=http://readarr:8787
      - homepage.widget.key=$READARR_API_KEY
      - homepage.widget.fields=["wanted", "queued", "books"]


  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: always
    networks:
      - internal
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - 8191:8191

    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.rule=PathPrefix(`/flaresolverr`)
      - traefik.http.routers.flaresolverr.tls=true
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8191



  # image used for vpn killswitch network
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8088:8088 # qbittorrent http web ui
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      # see https://github.com/qdm12/gluetun-wiki for more details
      # example envs based on https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      - VPN_SERVICE_PROVIDER=protonvpn # define the vpn provider
      - OPENVPN_USER=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - VPN_PORT_FORWARDING=on
      - FIREWALL_VPN_INPUT_PORTS=8088
      - EXTRA_SUBNETS=192.168.178.0/24
      - FIREWALL_ALLOWED_SUBNETS=192.168.178.0/24
      - LISTENING_ADDRESS=0.0.0.0
      - VPN_INPUT_PORTS=8080,63758
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8088/api/v2/app/setPreferences 2>&1'
      #- IPV6_ENABLED=false
    volumes:
      - /docker-configs/gluetun:/gluetun
    security_opt:
     - no-new-privileges:true
    restart: unless-stopped
    networks:
      - internal


  # image used to download stuff; run over gluetun network (vpn killswitch)
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    healthcheck:
      # Container may fail if the vpn's token expired, so mark as unhealthy when there is no internet connection
      # see: https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8088", "https://google.com" ]
      interval: 30s
      retries: 10
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8088
    volumes:
      - /docker-configs/qbittorrent:/config
      - $TORRENT_PATH:/data/torrents

    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun # use the gluetun container network (vpn killswitch)
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TIMEZONE
      - PORT=5055 #optional
    ports:
      - 5055:5055
    security_opt:
     - no-new-privileges:true
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.moritzpalm.com`) || Host(`overseerr.local.moritzpalm.com`)"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certresolver=cloudflare"
      - "traefik.http.routers.overseerr.service=overseerr"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - homepage.group=Downloader
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://overseerr.moritzpalm.com
      - homepage.description=Media Request
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr:5055
      - homepage.widget.key=$OVERSEERR_API_KEY
      - homepage.widget.fields=["pending", "approved", "available", "processing"]


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker-configs/bazarr:/config
      - $MEDIA_PATH/media/movies:/movies #optional
      - $MEDIA_PATH/media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped


  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3-3.0.0.1124
    ports:
      - "6969:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - internal
    volumes:
      - /docker-configs/whisparr:/config
      - $MEDIA_PATH/:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mamapi:
    image: elforkhead/mamapi:latest
    # also available at ghcr.io/elforkhead/mamapi:latest
    network_mode: "service:gluetun"
    volumes:
      - ./mamapi/data:/data
    environment:
      TZ: Etc/UTC
      MAM_ID: $MAM_SESSION_ID

  #seedboxapi:
  #  image: myanonamouse/seedboxapi
  #  container_name: seedboxapi
   # network_mode: "service:gluetun"
   # entrypoint: sh -c "rm -f /config/MAM.cookies && exec /wrapper.sh"
   # volumes:
   #   - /docker-configs/seedboxapi:/config
   # depends_on:
   #   gluetun:
   #     condition: service_healthy
    #environment:
    #  - PUID=1000
     # - PGID=1000
      #- TZ=Europe/Berlin
      #- DEBUG=1
      #- mam_id=$MAM_SESSION_ID
      #- interval=1





