networks:
  external:
    external: true

services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - stack.env
    networks:
      - external

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - stack.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
       - external

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - stack.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipes.entrypoints=websecure"
      - "traefik.http.routers.recipes.rule=Host(`recipes.moritzpalm.com`)"
      - "traefik.http.routers.recipes.tls=true"
      - "traefik.http.routers.recipes.tls.certresolver=cloudflare"
      - "traefik.http.routers.recipes.service=recipes"
      - "traefik.http.services.recipes.loadbalancer.server.port=80"
      - "traefik.http.middlewares.recipes.headers.customrequestheaders.Host=recipes.moritzpalm.com"
      - "traefik.http.middlewares.recipes.headers.customrequestheaders.X-Forwarded-Proto=https"

volumes:
  nginx_config:
  staticfiles: