version: '3.9'

networks:
  internal:
    external: true
  external:
    external: true

services:
  plex-server:
    container_name: plex
    image: 'plexinc/pms-docker:latest'
    restart: unless-stopped
    networks:
      - internal
      - external
    environment:
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM=claim-cNn-PxM_2oMvFseuCHi2
      - HOSTNAME="PLEX_SERVER"
    ports:
       - 32401:32400/tcp
       - 32401:32400/udp
       - 3005:3005/tcp
       - 8324:8324/tcp
       - 32469:32469/tcp
       - 1900:1900/udp
       - 32410:32410/udp
       - 32412:32412/udp
       - 32413:32413/udp
       - 32414:32414/udp
    devices:
      - "/dev/dri:/dev/dri" # Binds the Intel Quicksync decoder to Plex HW Transcode

    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - /media/storage/media:/data/media
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=https://app.plex.tv
      - homepage.description=Media Server
      - homepage.widget.type=plex
      - homepage.widget.url=http://192.168.178.174/:32400
      - homepage.widget.key=$PLEX_API_KEY
      - homepage.widget.fields=["streams", "movies", "tv", "albums"]

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8181:8181


  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: 1000:1000
    volumes:
      - /docker-configs/jellyfin:/config
      - ./cache:/cache
      - type: bind
        source: /media/storage/media/
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    devices:
      - "/dev/dri:/dev/dri" # Binds the Intel Quicksync decoder to Jellyfin HW Transcode


  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    #user: 1000:1000
    ports:
      - 13378:80
    volumes:
      - $MEDIA_PATH/audiobooks:/audiobooks
      - $MEDIA_PATH/podcasts:/podcasts
      - /docker-configs:/config
      - ./metadata:/metadata
    environment:
      - TZ=Europe/Berlin


  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /docker-configs:/config
    ports:
      - 8083:8080
      - 8282:8181
      - 8081:8081
    restart: unless-stopped

    