services:

   homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    container_name: homepage
    environment:
      - HOMEPAGE_VAR_TITLE=MServer
      - HOMEPAGE_VAR_SEARCH_PROVIDER=google
      - HOMEPAGE_VAR_HEADER_STYLE=boxed
      - HOMEPAGE_VAR_WEATHER_CITY=Erlangen
      - HOMEPAGE_VAR_WEATHER_LAT=49.5897
      - HOMEPAGE_VAR_WEATHER_LONG=11.0120
      - HOMEPAGE_VAR_WEATHER_TIME=Europe/Berlin
      - HOMEPAGE_VAR_WEATHER_UNIT=metric
      - PORT=3123
      - HOMEPAGE_ALLOWED_HOSTS=home.moritzpalm.com,${LAN_IP}:3123,${HOST_IP}:3123
    volumes:
      - ${CONFIG_PATH}/homepage:/app/config
      - ${CONFIG_PATH}/homepage/data:/data
    depends_on:
      - dockerproxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - ${HOST_IP}:3123:3123
    #command: [sh, -c, "cp -n /app/config/tpl/*.yaml /app/config && node server.js"]
    networks:
      - internal
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=tunnel"
      - "traefik.http.routers.homepage.rule=Host(`home.moritzpalm.com`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.middlewares=chain-public@file"
      - "traefik.http.routers.homepage.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3123"
      - "traefik.docker.network=external"


   dockerproxy:
    image: tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    container_name: homepage_dockerproxy
    environment:
      - CONTAINERS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - internal


networks:
  external:
    external: true
  internal:
    external: true