services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
    env_file: 
      - path: .env
      - required: true

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network
