services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:lts@sha256:4f156214efb9260c7324bc73af37e4c57499259c25496f16341886cef3f9e268
    restart: always
    command: --admin-password-file /run/secrets/portainer_admin_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /srv/compose/portainer/admin_password.txt:/run/secrets/portainer_admin_password:ro

    ports:
      - ${HOST_IP}:9443:9443
    environment:
      - PORTAINER_LICENSE_KEY=${PORTAINER_LICENSE_KEY}
    security_opt:
      - no-new-privileges:true
    labels:
      - "homepage.group=Monitoring"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer"
      - "homepage.href=https://${HOST_IP}:9443"
      - "homepage.description=Container management"


volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network
