services:
  vikunja:
    image: vikunja/vikunja:2.4.0@sha256:1a5dd2d410b5359f689c77bbd1c66742cde1993f82d4adfe9aefa400ff1dd833
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://${HOST_IP}:3456
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_POSTGRES_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_SECRET: ${VIKUNJA_JWT_SECRET}
    ports:
      - ${HOST_IP}:3456:3456
    volumes:
      - ${DATABASE_DIR}/vikunja-files:/app/vikunja/files
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "homepage.group=Productivity"
      - "homepage.name=Vikunja"
      - "homepage.icon=vikunja"
      - "homepage.href=http://${HOST_IP}:3456"
      - "homepage.description=Task manager"
  db:
    image: postgres:17@sha256:0af65001d05296a2ead57ac4a6412433d8913d1bb5d0c88435a7d1e1ee5cb04b
    container_name: vikunja_db
    environment:
      POSTGRES_PASSWORD: ${VIKUNJA_POSTGRES_PASSWORD}
      POSTGRES_USER: vikunja
    volumes:
      - ${DATABASE_DIR}/vikunja:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s
