services:

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    # using a vpn here is mainly to use the existing MAM Session which is dynamically updated by the mousehole container
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config # database and Prowlarr configs
    security_opt:
      - no-new-privileges:true 
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:9696/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "homepage.group=Downloads"
      - "homepage.name=Prowlarr"
      - "homepage.icon=prowlarr"
      - "homepage.href=http://${HOST_IP}:9696"
      - "homepage.description=Indexer manager"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      gluetun:
        condition: service_healthy
    ports: 
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_PATH}/sonarr:/config # database and Sonarr configs
      - ${STORAGE_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
       - no-new-privileges:true 
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8989/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - arr
    labels:
      - "homepage.group=Arr"
      - "homepage.name=Sonarr"
      - "homepage.icon=sonarr"
      - "homepage.href=http://${HOST_IP}:8989"
      - "homepage.description=TV series"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      gluetun:
        condition: service_healthy
    ports: 
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${STORAGE_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - arr
    labels:
      - "homepage.group=Arr"
      - "homepage.name=Radarr"
      - "homepage.icon=radarr"
      - "homepage.href=http://${HOST_IP}:7878"
      - "homepage.description=Movies"

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr    
    depends_on:
      gluetun:
        condition: service_healthy
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${STORAGE_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8686/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - arr
    labels:
      - "homepage.group=Arr"
      - "homepage.name=Lidarr"
      - "homepage.icon=lidarr"
      - "homepage.href=http://${HOST_IP}:8686"
      - "homepage.description=Music"


  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /run
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Berlin
    security_opt:
      - no-new-privileges:true
    labels:
      - "homepage.group=Downloads"
      - "homepage.name=FlareSolverr"
      - "homepage.icon=flaresolverr"
      - "homepage.href=http://${HOST_IP}:8191"
      - "homepage.description=Cloudflare bypass"


  # image used for vpn killswitch network
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add: # docker drops all cap execpt added 
      - NET_ADMIN
    ports:
      - 8088:8088 # qbittorrent http web ui
      - 5030:5030 # soulseek web ui
      - 5031:5031 # soulseek https web ui
      - 9696:9696 # prowlarr web ui
      - 8191:8191 # flaresolverr web ui
      - 5010:5010 # Mousehole port
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      # see https://github.com/qdm12/gluetun-wiki for more details
      # example envs based on https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      - VPN_SERVICE_PROVIDER=protonvpn # define the vpn provider
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=on
      - FIREWALL_INPUT_PORTS=8088,5030,5031,9696,8191
      - EXTRA_SUBNETS=192.168.178.0/24
      - FIREWALL_ALLOWED_SUBNETS=192.168.178.0/24
      - LISTENING_ADDRESS=0.0.0.0
      - VPN_INPUT_PORTS=8080,63758
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8088/api/v2/app/setPreferences 2>&1'
      #- IPV6_ENABLED=false
    volumes:
      - ${CONFIG_PATH}/gluetun:/gluetun
    security_opt:
     - no-new-privileges:true
    restart: unless-stopped
    networks:
      - arr
      - default
      - media_network


  # image used to download stuff; run over gluetun network (vpn killswitch)
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    healthcheck:
      # Container may fail if the vpn's token expired, so mark as unhealthy when there is no internet connection
      # see: https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8088", "https://google.com" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
      - WEBUI_PORT=8088
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${STORAGE_PATH}:/data
    env_file:
      - ./.env
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun # use the gluetun container network (vpn killswitch)
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "homepage.group=Downloads"
      - "homepage.name=qBittorrent"
      - "homepage.icon=qbittorrent"
      - "homepage.href=http://${HOST_IP}:8088"
      - "homepage.description=Torrent client"

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    user: "1000:1000"
    depends_on:
      gluetun:
        condition: service_healthy
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
      - PORT=5055 #optional
    security_opt:
     - no-new-privileges:true
    volumes:
      - ${CONFIG_PATH}/overseerr:/app/config
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - arr
      - media_network
    labels:
      - "homepage.group=Requests"
      - "homepage.name=Overseerr"
      - "homepage.icon=overseerr"
      - "homepage.href=http://${HOST_IP}:5055"
      - "homepage.description=Media requests"


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      gluetun:
        condition: service_healthy
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${STORAGE_PATH}:/data
    tmpfs:
      - /run:uid=1000,gid=1000,exec
    restart: unless-stopped
    networks:
      - arr
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:6767/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    labels:
      - "homepage.group=Arr"
      - "homepage.name=Bazarr"
      - "homepage.icon=bazarr"
      - "homepage.href=http://${HOST_IP}:6767"
      - "homepage.description=Subtitles"


  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3
    depends_on:
      gluetun:
        condition: service_healthy
    ports:
      - 6969:6969
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_PATH}/whisparr:/config
      - ${STORAGE_PATH}:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "homepage.group=Arr"
      - "homepage.name=Whisparr"
      - "homepage.icon=whisparr"
      - "homepage.href=http://${HOST_IP}:6969"
      - "homepage.description=Adult content"
    networks:
      - arr
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:6969/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  mousehole:
    image: tmmrtn/mousehole:latest
    network_mode: "service:gluetun"
    environment:
      TZ: Europe/Berlin
    volumes:
      # persist cookie data across container restarts
      - "${CONFIG_PATH}/mousehole:/srv/mousehole"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true


  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    user: 1000:1000
    volumes:
      - ${CONFIG_PATH}/slskd:/app
      - ${MEDIA_PATH}/music:/music:rw
      - ${SOULSEEK_PATH}:/downloads:rw
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun # use the gluetun container network (vpn killswitch)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5030"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "homepage.group=Music"
      - "homepage.name=slskd"
      - "homepage.icon=slskd"
      - "homepage.href=http://${HOST_IP}:5030"
      - "homepage.description=Soulseek client"


  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - ${CONFIG_PATH}/profilarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    restart: unless-stopped
    networks:
      - arr
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:6868/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    labels:
      - "homepage.group=Arr"
      - "homepage.name=Profilarr"
      - "homepage.icon=profilarr"
      - "homepage.href=http://${HOST_IP}:6868"
      - "homepage.description=Quality profiles"

  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
    ports:
      - 8787:8787
    volumes:
      - ${CONFIG_PATH}/bookshelf:/config
      - ${STORAGE_PATH}:/data
    security_opt:
       - no-new-privileges:true 
    restart: unless-stopped
    networks:
      - arr
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8787"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "homepage.group=Books"
      - "homepage.name=Bookshelf"
      - "homepage.icon=bookshelf-traccar"
      - "homepage.href=http://${HOST_IP}:8787"
      - "homepage.description=Book tracker"

  audiobookrequest:
    image: markbeep/audiobookrequest:1
    container_name: audiobookrequest
    user: "1000:1000"
    ports: 
      - 8000:8000
    volumes: 
      - ${CONFIG_PATH}/audiobookrequest:/config
    environment:
      - ABR_APP__DEFAULT_REGION=de
      - ABR_APP__OPENAPI_ENABLED=true
      - ABR_APP__INIT_ROOT_USERNAME=${ABR_USERNAME}
      - ABR_APP__INIT_ROOT_PASSWORD=${ABR_PASSWORD}
      - ABR_APP__FORCE_LOGIN_TYPE=forms # to be changed when authentik is set up
      - TZ=Europe/Berlin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - arr
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "homepage.group=Books"
      - "homepage.name=AudioBookRequest"
      - "homepage.icon=audiobookshelf"
      - "homepage.href=http://${HOST_IP}:8000"
      - "homepage.description=Audiobook requests"

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    user: "1000:1000"
    ports:
      - "2468:2468"
    volumes:
      - ${CONFIG_PATH}/cross-seed:/config
      - ${STORAGE_PATH}:/data
    command: daemon
    restart: unless-stopped
    networks:
      - arr
    security_opt:
      - no-new-privileges:true
    



networks:
  arr:
    external: true
  media_network:
    external: true

