services:

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config # database and Prowlarr configs
    security_opt:
      - no-new-privileges:true 
    ports:
      - 9696:9696/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:9696/prowlarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped
      
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/sonarr:/config # database and Radarr configs
      - ${MEDIA_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
       - no-new-privileges:true 
    ports:
      - 8989:8989/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8989/sonarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped

 
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true 
    ports:
      - 7878:7878/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/radarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped


  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${MEDIA_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true 
    expose:
      - 8686/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8686/lidarr/ping" ]
      interval: 30s
      retries: 10
    ports:
      - 8686:8686/tcp # web ui
    restart: unless-stopped
      

  # image used to scan for books
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/readarr:/config
      - ${MEDIA_PATH}:/data # location of media and qbittorrent download folder
    security_opt:
     - no-new-privileges:true
    ports:
      - 8787:8787/tcp # web ui
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8787/readarr/ping" ]
      interval: 30s
      retries: 10
    restart: unless-stopped
 

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: always
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Berlin
    ports:
      - 8191:8191


  # image used for vpn killswitch network
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8088:8088 # qbittorrent http web ui
      - 5030:5030 # soulseek web ui
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      # see https://github.com/qdm12/gluetun-wiki for more details
      # example envs based on https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      - VPN_SERVICE_PROVIDER=protonvpn # define the vpn provider
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=on
      - FIREWALL_VPN_INPUT_PORTS=8088
      - EXTRA_SUBNETS=192.168.178.0/24
      - FIREWALL_ALLOWED_SUBNETS=192.168.178.0/24
      - LISTENING_ADDRESS=0.0.0.0
      - VPN_INPUT_PORTS=8080,63758
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8088/api/v2/app/setPreferences 2>&1'
      #- IPV6_ENABLED=false
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    security_opt:
     - no-new-privileges:true
    restart: unless-stopped


  # image used to download stuff; run over gluetun network (vpn killswitch)
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    healthcheck:
      # Container may fail if the vpn's token expired, so mark as unhealthy when there is no internet connection
      # see: https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8088", "https://google.com" ]
      interval: 30s
      retries: 10
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${TORRENT_PATH}:/data/torrents
    env_file:
      - ./.env
      - ./qbittorrent.env

    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun # use the gluetun container network (vpn killswitch)
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
      - PORT=5055 #optional
    ports:
      - 5055:5055
    security_opt:
     - no-new-privileges:true
    volumes:
      - ${CONFIG_DIR}/overseerr:/app/config
    restart: unless-stopped



  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_PATH}/movies:/movies #optional
      - ${MEDIA_PATH}/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped


  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3-3.0.0.1124
    ports:
      - "6969:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${CONFIG_DIR}/whisparr:/config
      - ${MEDIA_PATH}:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mamapi:
    image: elforkhead/mamapi:latest
    # also available at ghcr.io/elforkhead/mamapi:latest
    container_name: mam_api
    network_mode: "service:gluetun"
    volumes:
      - ./mamapi/data:/data
    environment:
      TZ: Etc/UTC
      MAM_ID: ${MAM_SESSION_ID}


  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    user: 1000:1000
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete
      - SLSKD_SHARED_DIR=/music,/ebooks
    volumes:
      - ${CONFIG_DIR}/slskd:/app
      - ${MEDIA_PATH}/music:/music:rw
      - ${MEDIA_PATH}/books:/ebooks:rw
      - ${TORRENT_PATH}:/downloads:rw
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun # use the gluetun container network (vpn killswitch)



  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    user: 1000:1000
    environment:
      - TZ=Europe/Berlin
      - SCCRIPT_INTERVAL=300
    volumes:
      - ${TORRENT_PATH}/downloads/complete:/downloads
      - ${CONFIG_DIR}/soularr:/data
   



